# Используем образ Go версии 1.21.4
FROM golang:1.21.4 AS build

# Устанавливаем рабочую директорию внутри контейнера
WORKDIR /shortener-web

# Копируем файлы go.mod и go.sum и устанавливаем зависимости
COPY go.mod go.sum ./
RUN go mod download

# Копируем исходный код проекта в контейнер
COPY . .

# Собираем приложение
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o main ./cmd

# Создаем окончательный образ, используем легковесный образ alpine
FROM alpine:latest  

# Устанавливаем пакеты необходимые для запуска нашего приложения
RUN apk --no-cache add ca-certificates

# Устанавливаем рабочую директорию
WORKDIR /root/

# Копируем собранное приложение из предыдущего образа
COPY --from=build /shortener-web/ .

EXPOSE 8080

# Определяем команду для запуска приложения
CMD ["./main"]
